server:
  shutdown: graceful

spring:
  application:
    name: blog-search-application
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379

kakao:
  api:
    url: https://dapi.kakao.com
    key: 9f39af5200cc763ed4880c2b52b73645

naver:
  api:
    url: https://openapi.naver.com
    client-id: dzwU0GtRwpmQV71Om1m4
    secret: c9_u4IAR1q

springdoc:
  swagger-ui:
    path: /api-docs
    disable-swagger-default-url: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 100
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 300s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - com.github.asyu.homework.common.exception.CommunicationFailureException
  instances:
    kakao:
      baseConfig: default
    naver:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 200
      retryExceptions:
        - com.github.asyu.homework.common.exception.CommunicationFailureException
  instances:
    kakao:
      baseConfig: default
    naver:
      baseConfig: default
